@extends('trashcan::layouts.app-' . config('trashcan.css_framework', 'bootstrap'))
@section('content')
@include('trashcan::partials.' . config('trashcan.css_framework') . '.sidebar')
@php $bs = config('trashcan.css_framework') === 'bootstrap'; @endphp

@if($bs)
<div class="main-content p-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div><h1 class="h3 mb-1"><i class="bi bi-trash3 text-secondary me-2"></i>{{ $activeModel['name'] }} Trash</h1><p class="text-muted mb-0">{{ $items->total() }} items</p></div>
        <div class="d-flex gap-2"><span id="selectedCount" class="text-muted me-2"></span>
            @if($items->count())<form action="{{ route('trashcan.bulk-restore', $encoded) }}" method="POST" class="d-inline">@csrf<input type="hidden" name="ids" id="restoreIds"><button class="btn btn-restore btn-sm text-white bulk-btn" disabled onclick="document.getElementById('restoreIds').value=JSON.stringify(getSelectedIds())"><i class="bi bi-arrow-counterclockwise"></i> Restore</button></form>
            <form action="{{ route('trashcan.bulk-force-delete', $encoded) }}" method="POST" class="d-inline">@csrf @method('DELETE')<input type="hidden" name="ids" id="deleteIds"><button class="btn btn-danger btn-sm bulk-btn" disabled onclick="return confirm('Delete?')&&(document.getElementById('deleteIds').value=JSON.stringify(getSelectedIds()))"><i class="bi bi-trash3"></i> Delete</button></form>
            <form action="{{ route('trashcan.empty-trash', $encoded) }}" method="POST" class="d-inline">@csrf @method('DELETE')<button class="btn btn-outline-danger btn-sm" onclick="return confirm('Empty all?')"><i class="bi bi-trash3-fill"></i> Empty</button></form>@endif
        </div>
    </div>
    <div class="card shadow-sm border-0 mb-4"><div class="card-body"><form method="GET" class="row g-3"><div class="col-md-4"><div class="input-group"><span class="input-group-text"><i class="bi bi-search"></i></span><input type="text" name="search" class="form-control" placeholder="Search..." value="{{ request('search') }}"></div></div><div class="col-md-3"><input type="date" name="from" class="form-control" value="{{ request('from') }}"></div><div class="col-md-3"><input type="date" name="to" class="form-control" value="{{ request('to') }}"></div><div class="col-md-2"><button class="btn btn-primary w-100">Filter</button></div></form></div></div>
    @if(session('success'))<div class="alert alert-success alert-dismissible fade show"><i class="bi bi-check-circle me-2"></i>{{ session('success') }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>@endif
    @if($items->count())<div class="card shadow-sm border-0"><div class="table-responsive"><table class="table table-hover mb-0"><thead class="table-light"><tr><th width="40"><input type="checkbox" class="form-check-input" onchange="toggleAll(this)"></th>@foreach($activeModel['columns'] as $col)<th><a href="{{ request()->fullUrlWithQuery(['sort'=>$col,'dir'=>request('dir')==='asc'?'desc':'asc']) }}" class="text-decoration-none text-dark">{{ ucwords(str_replace('_',' ',$col)) }}@if(request('sort')===$col)<i class="bi bi-arrow-{{ request('dir')==='asc'?'up':'down' }}"></i>@endif</a></th>@endforeach<th width="120" class="text-end">Actions</th></tr></thead><tbody>@foreach($items as $item)<tr><td><input type="checkbox" class="form-check-input item-checkbox" value="{{ $item->id }}"></td>@foreach($activeModel['columns'] as $col)<td>@if($col==='deleted_at')<span class="text-muted small">{{ $item->deleted_at->diffForHumans() }}</span>@else{{ Str::limit($item->{$col}, 50) }}@endif</td>@endforeach<td class="text-end"><form action="{{ route('trashcan.restore', [$encoded, $item->id]) }}" method="POST" class="d-inline">@csrf<button class="btn btn-sm btn-restore text-white"><i class="bi bi-arrow-counterclockwise"></i></button></form><form action="{{ route('trashcan.force-delete', [$encoded, $item->id]) }}" method="POST" class="d-inline">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" onclick="return confirm('Delete?')"><i class="bi bi-trash3"></i></button></form></td></tr>@endforeach</tbody></table></div></div><div class="mt-3">{{ $items->links() }}</div>@else<div class="card shadow-sm border-0 text-center py-5"><i class="bi bi-trash3 text-muted" style="font-size:4rem"></i><h5 class="mt-3 text-muted">No items</h5></div>@endif
</div>
@else
<main class="ml-72 min-h-screen p-8">
    <div class="flex justify-between items-center mb-6">
        <div><h1 class="text-2xl font-semibold text-gray-800 dark:text-white"><i class="ri-delete-bin-line text-gray-400 mr-2"></i>{{ $activeModel['name'] }} Trash</h1><p class="text-gray-500 mt-1">{{ $items->total() }} items</p></div>
        <div class="flex items-center gap-3"><span id="selectedCount" class="text-sm text-gray-500"></span>
            @if($items->count())<form action="{{ route('trashcan.bulk-restore', $encoded) }}" method="POST" class="inline">@csrf<input type="hidden" name="ids" id="restoreIds"><button class="bulk-btn px-4 py-2 bg-emerald-500 text-white text-sm rounded-lg disabled:opacity-50" disabled onclick="document.getElementById('restoreIds').value=JSON.stringify(getSelectedIds())"><i class="ri-arrow-go-back-line mr-1"></i>Restore</button></form>
            <form action="{{ route('trashcan.bulk-force-delete', $encoded) }}" method="POST" class="inline">@csrf @method('DELETE')<input type="hidden" name="ids" id="deleteIds"><button class="bulk-btn px-4 py-2 bg-red-500 text-white text-sm rounded-lg disabled:opacity-50" disabled onclick="return confirm('Delete?')&&(document.getElementById('deleteIds').value=JSON.stringify(getSelectedIds()))"><i class="ri-delete-bin-line mr-1"></i>Delete</button></form>
            <form action="{{ route('trashcan.empty-trash', $encoded) }}" method="POST" class="inline">@csrf @method('DELETE')<button class="px-4 py-2 border border-red-300 text-red-600 text-sm rounded-lg" onclick="return confirm('Empty?')"><i class="ri-delete-bin-fill mr-1"></i>Empty</button></form>@endif
        </div>
    </div>
    <div class="bg-white dark:bg-slate-800 rounded-xl shadow-sm p-4 mb-6"><form method="GET" class="flex flex-wrap gap-4"><div class="flex-1 min-w-[200px] relative"><i class="ri-search-line absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"></i><input type="text" name="search" placeholder="Search..." value="{{ request('search') }}" class="w-full pl-10 pr-4 py-2 border border-gray-200 dark:border-slate-600 rounded-lg bg-transparent dark:text-white"></div><input type="date" name="from" value="{{ request('from') }}" class="px-4 py-2 border border-gray-200 dark:border-slate-600 rounded-lg bg-transparent dark:text-white"><input type="date" name="to" value="{{ request('to') }}" class="px-4 py-2 border border-gray-200 dark:border-slate-600 rounded-lg bg-transparent dark:text-white"><button class="px-6 py-2 bg-indigo-600 text-white rounded-lg">Filter</button></form></div>
    @if(session('success'))<div class="mb-4 p-4 bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-lg text-green-800 dark:text-green-400"><i class="ri-check-line mr-2"></i>{{ session('success') }}</div>@endif
    @if($items->count())<div class="bg-white dark:bg-slate-800 rounded-xl shadow-sm overflow-hidden"><table class="w-full"><thead class="bg-gray-50 dark:bg-slate-700 border-b dark:border-slate-600"><tr><th class="p-4 w-10"><input type="checkbox" class="rounded" onchange="toggleAll(this)"></th>@foreach($activeModel['columns'] as $col)<th class="p-4 text-left text-sm font-medium text-gray-600 dark:text-gray-300"><a href="{{ request()->fullUrlWithQuery(['sort'=>$col,'dir'=>request('dir')==='asc'?'desc':'asc']) }}" class="hover:text-indigo-600">{{ ucwords(str_replace('_',' ',$col)) }}@if(request('sort')===$col)<i class="ri-arrow-{{ request('dir')==='asc'?'up':'down' }}-s-line"></i>@endif</a></th>@endforeach<th class="p-4 text-right w-32">Actions</th></tr></thead><tbody class="divide-y dark:divide-slate-700">@foreach($items as $item)<tr class="hover:bg-gray-50 dark:hover:bg-slate-700/50"><td class="p-4"><input type="checkbox" class="item-checkbox rounded" value="{{ $item->id }}"></td>@foreach($activeModel['columns'] as $col)<td class="p-4 text-sm text-gray-700 dark:text-gray-300">@if($col==='deleted_at')<span class="text-gray-400">{{ $item->deleted_at->diffForHumans() }}</span>@else{{ Str::limit($item->{$col}, 50) }}@endif</td>@endforeach<td class="p-4 text-right"><form action="{{ route('trashcan.restore', [$encoded, $item->id]) }}" method="POST" class="inline">@csrf<button class="p-2 text-emerald-600 hover:bg-emerald-50 dark:hover:bg-emerald-900/20 rounded-lg"><i class="ri-arrow-go-back-line"></i></button></form><form action="{{ route('trashcan.force-delete', [$encoded, $item->id]) }}" method="POST" class="inline">@csrf @method('DELETE')<button class="p-2 text-red-600 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg" onclick="return confirm('Delete?')"><i class="ri-delete-bin-line"></i></button></form></td></tr>@endforeach</tbody></table></div><div class="mt-4">{{ $items->links() }}</div>@else<div class="bg-white dark:bg-slate-800 rounded-xl shadow-sm py-20 text-center"><i class="ri-delete-bin-line text-6xl text-gray-200 dark:text-slate-600"></i><h5 class="mt-4 text-lg text-gray-500">No items</h5></div>@endif
</main>
@endif
@endsection